name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git Repo
        uses: actions/checkout@v2

      - name: Install
        run: |
          pip install -r requirements.txt

      - name: Test
        run: pytest

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: <path/to/artifact>
